print_usage() {
  echo -e "Usage:\n\nproj <component | global action> <action> [<action args>]\n"
  echo "global actions:"
  echo "  help"
  echo "  init - create a 'gcpprojfile'"
  echo "  deploy"
  echo "  start"
  echo "  stop"
  echo "  clear-all-logs"
  echo "api:"
  print_api_usage "  "
  echo "project:"
  print_project_usage "  "
  echo "db:"
  echo "  start-proxy"
  echo "  stop-proxy"
  echo "  view-proxy-log"
  echo "  connect"
  echo "  rebuild [test]"
  echo "webapp:"
  echo "  build"
  echo "  audit"
  echo "  start"
  echo "  stop"
  echo "  view-log"
  echo "work:"
  print_work_usage "  "
}
