print_usage() {
  echo -e "Usage:\n\nproj <component | global action> <action> [<action args>]\n"
  echo "global actions:"
  echo "  help <component>: Prints this help, or component specific help."
  echo "go:"
  print_go_usage "  "
  echo "local:"
  print_local_usage "  "
  echo "project:"
  print_project_usage "  "
  echo "sql:"
  print_sql_usage "  "
  echo "webapp:"
  print_webapp_usage "  "
  echo "work:"
  print_work_usage "  "
}
