print_usage() {
  echo -e "Usage:\n\nproj <component | global action> <action> [<action args>]\n"
  echo "global actions:"
  echo "  help"
  echo "  init - create a 'gcpprojfile'"
  echo "  deploy"
  echo "  start"
  echo "  stop"
  echo "  clear-all-logs"
  echo "api:"
  echo "  get-deps"
  echo "  build"
  echo "  start"
  echo "  stop"
  echo "  view-log"
  echo "db:"
  echo "  start-proxy"
  echo "  stop-proxy"
  echo "  view-proxy-log"
  echo "  connect"
  echo "  rebuild [test]"
  echo "webapp:"
  echo "  build"
  echo "  audit"
  echo "  start"
  echo "  stop"
  echo "  view-log"
  echo "work:"
  echo "  start <desc> : creates work branch and switches to it"
  echo "  merge : merges current work branch commits to master and deletes work branch"
  echo "  show : shows committed changes since branch from 'master'"
}
